"""add identity verification system

Revision ID: a56aaede8006
Revises: 80dcc5759ec9
Create Date: 2026-08-24 14:24:09.279749+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56aaede8006'
down_revision: Union[str, None] = '80dcc5759ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('document_number_encrypted', sa.Text(), nullable=True),
    sa.Column('document_number_masked', sa.String(length=20), nullable=True),
    sa.Column('document_image_filename', sa.String(length=255), nullable=True),
    sa.Column('selfie_image_filename', sa.String(length=255), nullable=True),
    sa.Column('face_match_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('liveness_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('liveness_challenge_type', sa.String(length=30), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('verification_version', sa.String(length=10), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_verifications_deleted_at'), 'identity_verifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_identity_verifications_status'), 'identity_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_identity_verifications_user_id'), 'identity_verifications', ['user_id'], unique=True)
    op.add_column('users', sa.Column('identity_verification_status', sa.String(length=30), nullable=False, server_default='NOT_STARTED'))
    op.drop_column('users', 'is_identity_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_identity_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'identity_verification_status')
    op.drop_index(op.f('ix_identity_verifications_user_id'), table_name='identity_verifications')
    op.drop_index(op.f('ix_identity_verifications_status'), table_name='identity_verifications')
    op.drop_index(op.f('ix_identity_verifications_deleted_at'), table_name='identity_verifications')
    op.drop_table('identity_verifications')
    # ### end Alembic commands ###
