"""Add product status

Revision ID: 1742378c5c25
Revises: 2047e67e69c5
Create Date: 2026-07-27 05:02:20.739065+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1742378c5c25'
down_revision: Union[str, None] = '2047e67e69c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
