"""sync_missing_columns

Revision ID: 816a38778d17
Revises: a56aaede8006
Create Date: 2026-09-05 15:03:54.604317+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816a38778d17'
down_revision: Union[str, None] = 'a56aaede8006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('payout_id', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('earnings_period', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('payout_method', sa.String(length=30), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('routing_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disbursement_trx_id', sa.String(length=100), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_owner_id'), 'payouts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_payouts_payout_id'), 'payouts', ['payout_id'], unique=True)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('recently_viewed',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product_recently_viewed')
    )
    op.create_index(op.f('ix_recently_viewed_product_id'), 'recently_viewed', ['product_id'], unique=False)
    op.create_index(op.f('ix_recently_viewed_user_id'), 'recently_viewed', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('gateway_trx_id', sa.String(length=100), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('service_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('escrow_status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refund_trx_id', sa.String(length=50), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_owner_id'), 'payments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.add_column('products', sa.Column('discount_percentage', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('products', sa.Column('offer_title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('offer_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('reviews', sa.Column('status', sa.String(length=20), server_default=sa.text("'published'"), nullable=False))
    op.add_column('reviews', sa.Column('reported_by', sa.UUID(), nullable=True))
    op.add_column('reviews', sa.Column('report_reason', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('action_taken', sa.String(length=50), nullable=True))
    op.add_column('reviews', sa.Column('action_note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'users', ['reported_by'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'identity_verification_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'identity_verification_status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'NOT_STARTED'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'action_note')
    op.drop_column('reviews', 'action_taken')
    op.drop_column('reviews', 'report_reason')
    op.drop_column('reviews', 'reported_by')
    op.drop_column('reviews', 'status')
    op.drop_column('products', 'offer_active')
    op.drop_column('products', 'offer_title')
    op.drop_column('products', 'discount_percentage')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_owner_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_recently_viewed_user_id'), table_name='recently_viewed')
    op.drop_index(op.f('ix_recently_viewed_product_id'), table_name='recently_viewed')
    op.drop_table('recently_viewed')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_payout_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_owner_id'), table_name='payouts')
    op.drop_table('payouts')
    # ### end Alembic commands ###
